'\" t
.\"  Title: \fBeXo\fR
.\"  Author: Blaze <blaze@vivaldi.net>
.\"  Language: English
.TH EXO 1 "Dec 20, 2016"
.SH NAME
exo-player \- Exoskeleton (GUI) for moc player
.SH DESCRIPTION
GUI for moc player also known as mocp\&. Has experimental support of Cmus player\&.
.PP
Supports scrobbling, shows lyrics from web, stores bookmarks, detects tag editors\&.
.SH OPTIONS
.TP
.B \-b or \-\-background
Run in background mode (without GUI)\&.
.TP
.B \-d
Same as above\&.
.TP
.B \-f or \-\-force\-reauth
Force auth to audioscrobbler service via CLI\&. You'll get new session key\&.
.TP
To enable proxy use the system variable $http_proxy
.SH AUTHOR
This manual page was written by Blaze <blaze@vivaldi\&.net>
