'\" t
.\"  Title: \fBeXo\fR
.\"  Author: Blaze <blaze@vivaldi.net>
.\"  Language: English
.TH EXO 1 "Jul 19, 2024"
.SH NAME
eXo \- exoskeleton (GUI) for MOC player
.SH DESCRIPTION
GUI for MOC player also known as mocp\&. Has experimental support of CMus player\&.
.PP
Supports scrobbling, shows lyrics from web, stores bookmarks, detects tag editors\&.
.SH OPTIONS
.TP
.B \-b or \-\-background
Run in the background (with no GUI)\&.
.TP
.B \-d
Same as above\&.
.TP
.B \-c or \-\-use\-cmus
Run with CMus player interface\&.
.TP
.B \-s or \-\-use\-spotify
Run with Spotify player interface\&. This way app can run in parallel with other interfaces as a second process\&.
.TP
.B \-f or \-\-force\-reauth
Force reauth to audioscrobbler service via CLI\&. You'll get a new session key\&. No password is stored anywhere\&.
.TP
To enable proxy use the system variable $http_proxy
.SH AUTHOR
This manual page was written by Blaze <blaze@vivaldi\&.net>
