#! /usr/bin/env python3
# Copyright (c) 2020 Blaze <blaze@vivaldi.net>
# Licensed under the GNU General Public License, version 3 or later.
# See the file http://www.gnu.org/copyleft/gpl.txt.

import os
import re
import subprocess
import notify2


def get_year(path):
    strings = re.split(r'([12]{1}[09]{1}\d{2})', path, 1)
    return strings[1] if len(strings) > 1 else 'none'


def get_cover_path(path):
    if os.path.exists(path):
        entries = os.listdir(path)
        for entry in entries:
            if re.match(r'([^\s]+(?=\.(jpg|jpeg|png)))', entry):
                return "{}/{}".format(path, entry)
    return ''


def main():
    output = subprocess.getoutput(
        "mocp -Q '{{%file}}%artist <i><year></i> %album\n<b>%song (%tt)</b>'")
    m = re.match(r'\{\{(.*?)\}\}(.*)', output, re.DOTALL)
    if not m:
        os.sys.exit(1)  # input doesn't match
    dir = m.group(1).rsplit('/', 1)[0]
    osd = m.group(2).replace('<year>', get_year(dir)).replace('&', '&amp;')\
        .replace(' ()', '')
    if not notify2.init('eXo'):
        os.sys.exit(1)  # notify2 is out of reach
    ni = notify2.Notification('music on console', osd, get_cover_path(dir))
    ni.timeout = 8000
    if not ni.show():
        os.sys.exit(1)  # notify2 is not operational


if __name__ == '__main__':
    main()
